Source    = \
	Quantity.java \
	Unit.java \
	UnitManager.java \
        XmlUtil.java \
	display_symbols.txt \
	unit_aliases.txt \
	witsmlUnitDict-2.2.xml \

Main = UnitManager

include $(DEV_HOME)/Uom/Makefile